from enum import  Enum

class CONTEXT_STATE(Enum):
    INIT_STATE = 0
    DELETE_STATE = 1
    INSERT_STATE = 2
    UPDATE_STATE = 3
    JOIN_IN_UPDATE_STATE = 4
    SELECT_IN_INSERT_STATE = 5
    SELECT_IN_UPDATE_STATE = 6
    SELECT_STATE = 7
    SUB_SELECT_STATE = 8
    JOIN_IN_SELECT_STATE = 9
    JOIN_IN_SUB_SELECT_STATE = 10
    CORR_IN_SELECT_STATE = 11
    CORR_SUB_SELECT_STATE = 12
    SUB_QUERY_STATE = 13

class CURRENT_OBJ_STATE(Enum):
    IN_CREATE_STATE = 0
    NO_LABEL_STATE = 1